# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('project_manager', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=60)),
                ('investor', models.CharField(max_length=30)),
                ('cost', models.CharField(max_length=50)),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
