# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=30)),
                ('db_ip', models.CharField(max_length=40)),
                ('db_port', models.IntegerField(max_length=4)),
                ('kullanici_adi', models.TextField(max_length=10)),
                ('parola', models.TextField(max_length=10)),
            ],
        ),
    ]
