# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stark', '0003_auto_20180107_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseform',
            name='db_ip',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='databaseform',
            name='db_name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='databaseform',
            name='db_port',
            field=models.TextField(max_length=4),
        ),
        migrations.AlterField(
            model_name='databaseform',
            name='kullanici_adi',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='databaseform',
            name='parola',
            field=models.TextField(max_length=10),
        ),
    ]
